# Generated by Django 6.0.6 on 2026-06-28 06:03

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsmetric',
            name='category',
            field=models.CharField(blank=True, db_column='Category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='department',
            field=models.CharField(blank=True, db_column='Department', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='metric_name',
            field=models.CharField(db_column='MetricName', db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='metric_type',
            field=models.CharField(db_column='MetricType', max_length=100),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='recorded_at',
            field=models.DateTimeField(db_column='RecordedAt', db_index=True),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='value',
            field=models.CharField(db_column='Value', max_length=500),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=api.models.StringEnumIntegerField(db_column='Category', enum_mappings={'General': 0, 'Holiday': 1, 'Policy': 2}),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(db_column='Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.CharField(blank=True, db_column='CreatedBy', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_column='ExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=api.models.StringEnumIntegerField(db_column='Priority', default=1, enum_mappings={'High': 2, 'Low': 0, 'Medium': 1}),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_department',
            field=models.CharField(blank=True, db_column='TargetDepartment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_location',
            field=models.CharField(blank=True, db_column='TargetLocation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(db_column='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='visibility_scope',
            field=api.models.StringEnumIntegerField(db_column='VisibilityScope', default=0, enum_mappings={'Department': 1, 'Global': 0, 'Location': 2}),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(db_column='AssetName', max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=api.models.StringEnumIntegerField(db_column='Category', default=0, enum_mappings={'Accessories': 2, 'Laptop': 0, 'Mobile': 1}),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=api.models.StringEnumIntegerField(db_column='Condition', default=0, enum_mappings={'Damaged': 2, 'Good': 1, 'New': 0}),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(db_column='SerialNumber', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', default=0, enum_mappings={'Allocated': 1, 'Available': 0, 'Maintenance': 2}),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='allocated_on',
            field=models.DateTimeField(db_column='AllocatedOn'),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='asset_id',
            field=models.CharField(db_column='AssetId', max_length=128),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='condition_on_return',
            field=models.CharField(blank=True, db_column='ConditionOnReturn', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', max_length=128),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='return_reason',
            field=models.CharField(blank=True, db_column='ReturnReason', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='returned_on',
            field=models.DateTimeField(blank=True, db_column='ReturnedOn', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='break_hours',
            field=models.DecimalField(db_column='BreakHours', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_in',
            field=models.DateTimeField(blank=True, db_column='ClockIn', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_out',
            field=models.DateTimeField(blank=True, db_column='ClockOut', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateTimeField(db_column='Date', db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(db_column='OvertimeHours', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='productive_hours',
            field=models.DecimalField(db_column='ProductiveHours', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Absent': 1, 'Late': 3, 'OnLeave': 2, 'Present': 0}),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(blank=True, db_column='Email', db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, db_column='Experience', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_posting_id',
            field=models.CharField(blank=True, db_column='JobPostingId', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_column='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, db_column='NoticePeriod', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rating',
            field=models.DecimalField(db_column='Rating', decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='role_applied',
            field=models.CharField(blank=True, db_column='RoleApplied', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, db_column='Skills', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Applied': 0, 'Interviewing': 2, 'Offered': 3, 'Rejected': 4, 'Screening': 1}),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='cleared_by',
            field=models.CharField(blank=True, db_column='ClearedBy', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='cleared_on',
            field=models.DateTimeField(blank=True, db_column='ClearedOn', null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='department',
            field=api.models.StringEnumIntegerField(db_column='Department', db_index=True, enum_mappings={'Admin': 3, 'Finance': 2, 'HR': 1, 'IT': 0}),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='item_name',
            field=models.CharField(db_column='ItemName', max_length=500),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clearanceitem',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Cleared': 1, 'Pending': 0}),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='context',
            field=models.CharField(blank=True, db_column='Context', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='interaction_time',
            field=models.DateTimeField(db_column='InteractionTime', db_index=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='query',
            field=models.CharField(db_column='Query', max_length=2000),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='response',
            field=models.CharField(db_column='Response', max_length=4000),
        ),
        migrations.AlterField(
            model_name='copilotinteraction',
            name='was_helpful',
            field=models.BooleanField(db_column='WasHelpful', default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=api.models.StringEnumIntegerField(db_column='Category', db_index=True, enum_mappings={'AddressProof': 1, 'Education': 2, 'Experience': 3, 'IDProof': 0}),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_column='ExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_column='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rejection_reason',
            field=models.CharField(blank=True, db_column='RejectionReason', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Approved': 2, 'Missing': 0, 'Pending': 1, 'Rejected': 3}),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(blank=True, db_column='Url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='activation_code',
            field=models.CharField(blank=True, db_column='ActivationCode', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='activation_code_expiry',
            field=models.DateTimeField(blank=True, db_column='ActivationCodeExpiry', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='activation_code_status',
            field=models.CharField(db_column='ActivationCodeStatus', default='Unused', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=api.models.StringEnumIntegerField(db_column='Country', default=0, enum_mappings={'IN': 1, 'US': 0}),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, db_column='Department', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, db_column='Designation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_column='Email', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_demo',
            field=models.BooleanField(db_column='IsDemo', default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateTimeField(blank=True, db_column='JoiningDate', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.CharField(blank=True, db_column='ManagerId', db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(db_column='Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password_hash',
            field=models.CharField(blank=True, db_column='PasswordHash', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_status',
            field=models.CharField(db_column='RegistrationStatus', default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='registration_timestamp',
            field=models.DateTimeField(blank=True, db_column='RegistrationTimestamp', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=api.models.StringEnumIntegerField(db_column='Role', db_index=True, default=3, enum_mappings={'Admin': 0, 'Employee': 3, 'HR': 1, 'Manager': 2}),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Active': 0, 'Deleted': 2, 'Inactive': 1}),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='feedback_json',
            field=models.TextField(db_column='FeedbackJson'),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_value',
            field=models.DecimalField(db_column='CurrentValue', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='goal',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(blank=True, db_column='DueDate', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='progress_percentage',
            field=models.DecimalField(db_column='ProgressPercentage', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Completed': 2, 'InProgress': 1, 'NotStarted': 0}),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.DecimalField(db_column='TargetValue', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(db_column='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='goal',
            name='weight',
            field=models.DecimalField(db_column='Weight', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, db_column='Department', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience_required',
            field=models.CharField(blank=True, db_column='ExperienceRequired', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, db_column='Location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posted_date',
            field=models.DateTimeField(blank=True, db_column='PostedDate', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, db_column='SalaryRange', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Closed': 1, 'Open': 0}),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(db_column='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='available',
            field=models.DecimalField(db_column='Available', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=api.models.StringEnumIntegerField(db_column='LeaveType', enum_mappings={'Casual': 0, 'Personal': 2, 'Sick': 1}),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='pending',
            field=models.DecimalField(db_column='Pending', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_allowed',
            field=models.DecimalField(db_column='TotalAllowed', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used',
            field=models.DecimalField(db_column='Used', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approval_comments',
            field=models.CharField(blank=True, db_column='ApprovalComments', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.CharField(blank=True, db_column='ApprovedBy', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_on',
            field=models.DateTimeField(blank=True, db_column='ApprovedOn', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateTimeField(db_column='EndDate'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=api.models.StringEnumIntegerField(db_column='LeaveType', enum_mappings={'Casual': 0, 'Personal': 2, 'Sick': 1}),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(blank=True, db_column='Reason', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateTimeField(db_column='StartDate', db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Approved': 1, 'Cancelled': 3, 'Pending': 0, 'Rejected': 2}),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.DecimalField(db_column='TotalDays', decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='CompletedAt', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Completed': 1, 'Pending': 0}),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='task_id',
            field=models.CharField(db_column='TaskId', max_length=100),
        ),
        migrations.AlterField(
            model_name='onboardingchecklist',
            name='task_name',
            field=models.CharField(db_column='TaskName', max_length=200),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='role',
            field=models.CharField(db_column='Role', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='onboardingtemplate',
            name='tasks_json',
            field=models.TextField(db_column='TasksJson'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='allowances',
            field=models.DecimalField(db_column='Allowances', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='basic_pay',
            field=models.DecimalField(db_column='BasicPay', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='deductions',
            field=models.DecimalField(db_column='Deductions', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='esi',
            field=models.DecimalField(db_column='ESI', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='gross_pay',
            field=models.DecimalField(db_column='GrossPay', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='hra',
            field=models.DecimalField(db_column='HRA', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='income_tax',
            field=models.DecimalField(db_column='IncomeTax', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(db_column='NetPay', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='pay_period_end',
            field=models.DateTimeField(db_column='PayPeriodEnd'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='pay_period_start',
            field=models.DateTimeField(db_column='PayPeriodStart'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='pf',
            field=models.DecimalField(db_column='PF', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', default=0, enum_mappings={'Draft': 0, 'Paid': 1}),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='improvements',
            field=models.CharField(blank=True, db_column='Improvements', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='period',
            field=models.CharField(db_column='Period', max_length=50),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='rating',
            field=models.DecimalField(db_column='Rating', decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='review_date',
            field=models.DateTimeField(blank=True, db_column='ReviewDate', null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewer_id',
            field=models.CharField(db_column='ReviewerId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='strengths',
            field=models.CharField(blank=True, db_column='Strengths', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='approved_by',
            field=models.CharField(blank=True, db_column='ApprovedBy', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='approved_on',
            field=models.DateTimeField(blank=True, db_column='ApprovedOn', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='core_value',
            field=models.CharField(db_column='CoreValue', max_length=100),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='nominator_id',
            field=models.CharField(db_column='NominatorId', max_length=128),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='nominee_id',
            field=models.CharField(db_column='NomineeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='points',
            field=models.IntegerField(db_column='Points'),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='reason',
            field=models.CharField(db_column='Reason', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recognitionnomination',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Approved': 1, 'Pending': 0, 'Rejected': 2}),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='approved_by',
            field=models.CharField(blank=True, db_column='ApprovedBy', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='approved_on',
            field=models.DateTimeField(blank=True, db_column='ApprovedOn', null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='category',
            field=api.models.StringEnumIntegerField(db_column='Category', enum_mappings={'Food': 1, 'Medical': 2, 'Others': 3, 'Travel': 0}),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='comments',
            field=models.CharField(blank=True, db_column='Comments', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='currency',
            field=models.CharField(db_column='Currency', default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='date',
            field=models.DateTimeField(db_column='Date', db_index=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Approved': 1, 'Pending': 0, 'Rejected': 2}),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='approved_by',
            field=models.CharField(blank=True, db_column='ApprovedBy', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='approved_on',
            field=models.DateTimeField(blank=True, db_column='ApprovedOn', null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='last_working_date',
            field=models.DateTimeField(db_column='LastWorkingDate'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='reason',
            field=models.CharField(db_column='Reason', max_length=2000),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Approved': 1, 'Pending': 0, 'Rejected': 2}),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='submission_date',
            field=models.DateTimeField(db_column='SubmissionDate'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_to_id',
            field=models.CharField(blank=True, db_column='AssignedToId', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, db_column='AssignedToName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=api.models.StringEnumIntegerField(db_column='Category', db_index=True, default=0, enum_mappings={'Facilities': 3, 'Finance': 2, 'HR': 1, 'IT': 0}),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.CharField(db_column='Description', max_length=5000),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='employee_id',
            field=models.CharField(db_column='EmployeeId', db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=api.models.StringEnumIntegerField(db_column='Priority', db_index=True, default=1, enum_mappings={'High': 2, 'Low': 0, 'Medium': 1}),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='resolution_comments',
            field=models.CharField(blank=True, db_column='ResolutionComments', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', db_index=True, default=0, enum_mappings={'Closed': 3, 'InProgress': 1, 'Open': 0, 'Resolved': 2}),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(db_column='Title', max_length=500),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(db_column='UpdatedAt'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, db_column='DueDate', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(db_column='IsCompleted', db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.CharField(blank=True, db_column='UserId', db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='category',
            field=api.models.StringEnumIntegerField(db_column='Category', enum_mappings={'Compliance': 0, 'Leadership': 1, 'Technical': 2}),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='created_by_user_id',
            field=models.CharField(blank=True, db_column='CreatedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='created_by_user_name',
            field=models.CharField(blank=True, db_column='CreatedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='created_on',
            field=models.DateTimeField(blank=True, db_column='CreatedOn', null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='document_type',
            field=models.CharField(db_column='DocumentType', max_length=128),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='duration',
            field=models.IntegerField(db_column='Duration'),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='id',
            field=models.CharField(db_column='Id', default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='mandatory',
            field=models.BooleanField(db_column='Mandatory', default=False),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='modified_by_user_id',
            field=models.CharField(blank=True, db_column='ModifiedByUserId', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='modified_by_user_name',
            field=models.CharField(blank=True, db_column='ModifiedByUserName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='modified_on',
            field=models.DateTimeField(blank=True, db_column='ModifiedOn', null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='profile_picture',
            field=models.CharField(blank=True, db_column='ProfilePicture', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='progress_percentage',
            field=models.DecimalField(db_column='ProgressPercentage', decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='status',
            field=api.models.StringEnumIntegerField(db_column='Status', default=0, enum_mappings={'Completed': 2, 'InProgress': 1, 'NotStarted': 0}),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='title',
            field=models.CharField(db_column='Title', max_length=200),
        ),
    ]
